backend:
  name: git-gateway
  branch: single-page-theme
media_folder: static/icons
public_folder: /img
collections:
  - name: 'single-page'
    label: 'Single Page'
    folder: 'src/pages'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Brief", name: "brief", widget: "text" }
      - { label: "App Link", name: "appLink", widget: "string" }
      - { label: "About", name: "about", widget: "text" }
      - { label: "Achievements", name: "achievements", widget: "list", allow_add: true, field: { label: Achievement, name: achievement, widget: string } }
      - { label: "Experience", name: "experience", widget: "list", field: { label: Line, name: line, widget: text } }
      - { label: "Tutorials", name: "tutorials", widget: "list", fields: [{ label: Tutorial Id, name: id, widget: string }, { label: TutorialName, name: title, widget: string }] }
      - { label: "Testimonials", name: "testimonials", widget: "list", allow_add: true, fields: [{ label: Testimonial, name: testimonial, widget: text }, { label: Author, name: author, widget: string }] }
      - { label: "Social Media Links", name: "socialLinks", widget: "list", fields: [{ label: Social Platform, name: platform, widget: string }, { label: Link, name: link, widget: string }] }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Channel Link", name: "channel", widget: "string" }


