backend:
  name: git-gateway
  branch: single-page-theme
collectios:
  - name: 'single-page'
    label: 'Single Page'
    folder: 'src/pages'
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Brief", name: "brief", widget: "text"}
      - { label: "About", name: "about", widget: "text"}
      - {
          label: "Achievements",
          name: "achievements",
          widget: "list",
          allow_add: true,
          field: { label: Achievement, name: achievement, widget: string }
        }
      - { label: "Experience", name: "experience", widget: "text"}
      - {
          label: "Tutorials",
          name: "tutorials",
          widget: "list",
          field: { label: Tutorial, name: tutorial, widget: string }
        }
      - {
        label: "Testimonials",
          name: "testimonials",
          widget: "list",
          allow_add: true,
          fields:
            - { label: Testimonial, name: testimonial, widget: text }
      }


